"""add check constraints for data integrity

Revision ID: 18a0e48e3986
Revises: f9bee3a24296
Create Date: 2026-07-28 00:36:18.863790

Written by hand, not autogenerated: Alembic's autogenerate does not detect
CheckConstraint additions/removals (a documented limitation, not a
misconfiguration here) so this had to be authored manually.

Uses batch mode throughout because SQLite has no ALTER TABLE ADD CONSTRAINT
— batch_alter_table recreates each table under the hood with the new
constraint included, then copies the data across.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '18a0e48e3986'
down_revision: Union[str, Sequence[str], None] = 'f9bee3a24296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("meals") as batch_op:
        batch_op.create_check_constraint("ck_meals_calories_nonneg", "calories IS NULL OR calories >= 0")
        batch_op.create_check_constraint("ck_meals_protein_nonneg", "protein_g IS NULL OR protein_g >= 0")
        batch_op.create_check_constraint("ck_meals_carbs_nonneg", "carbs_g IS NULL OR carbs_g >= 0")
        batch_op.create_check_constraint("ck_meals_fat_nonneg", "fat_g IS NULL OR fat_g >= 0")

    with op.batch_alter_table("exercise_logs") as batch_op:
        batch_op.create_check_constraint("ck_exercise_duration_positive", "duration_min > 0")
        batch_op.create_check_constraint("ck_exercise_calories_nonneg", "calories_burned IS NULL OR calories_burned >= 0")

    with op.batch_alter_table("water_logs") as batch_op:
        batch_op.create_check_constraint("ck_water_amount_positive", "amount_ml > 0")

    with op.batch_alter_table("sleep_logs") as batch_op:
        batch_op.create_check_constraint("ck_sleep_hours_valid_range", "hours > 0 AND hours <= 24")

    with op.batch_alter_table("weight_logs") as batch_op:
        batch_op.create_check_constraint("ck_weight_positive", "weight_kg > 0")

    with op.batch_alter_table("goals") as batch_op:
        batch_op.create_check_constraint("ck_goals_target_positive", "target_value IS NULL OR target_value > 0")
        batch_op.create_check_constraint("ck_goals_end_after_start", "end_date IS NULL OR end_date >= start_date")


def downgrade() -> None:
    with op.batch_alter_table("goals") as batch_op:
        batch_op.drop_constraint("ck_goals_end_after_start", type_="check")
        batch_op.drop_constraint("ck_goals_target_positive", type_="check")

    with op.batch_alter_table("weight_logs") as batch_op:
        batch_op.drop_constraint("ck_weight_positive", type_="check")

    with op.batch_alter_table("sleep_logs") as batch_op:
        batch_op.drop_constraint("ck_sleep_hours_valid_range", type_="check")

    with op.batch_alter_table("water_logs") as batch_op:
        batch_op.drop_constraint("ck_water_amount_positive", type_="check")

    with op.batch_alter_table("exercise_logs") as batch_op:
        batch_op.drop_constraint("ck_exercise_calories_nonneg", type_="check")
        batch_op.drop_constraint("ck_exercise_duration_positive", type_="check")

    with op.batch_alter_table("meals") as batch_op:
        batch_op.drop_constraint("ck_meals_fat_nonneg", type_="check")
        batch_op.drop_constraint("ck_meals_carbs_nonneg", type_="check")
        batch_op.drop_constraint("ck_meals_protein_nonneg", type_="check")
        batch_op.drop_constraint("ck_meals_calories_nonneg", type_="check")
